spring:
    application:
        name: aula-spring-security
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 
                        client-secret: 
